from PIL import Image, ImageDraw, ImageFont
import os

def create_images_from_text(
    background_path,
    text_list,
    output_dir='output_images',
    font_path='/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf',
    font_size=40
):
    # Tạo thư mục lưu ảnh nếu chưa tồn tại
    os.makedirs(output_dir, exist_ok=True)
    for text in text_list:
        # Mở ảnh nền và chuyển sang RGBA
        img = Image.open(background_path).convert('RGBA')
        draw = ImageDraw.Draw(img)
        # Tạo font chữ
        font = ImageFont.truetype(font_path, font_size)
        # Chuẩn bị nội dung text, thêm dòng mô tả
        text1 = text + "\n trong chuỗi hàm PHP"
        # Tính toán kích thước text để căn giữa
        bbox = draw.multiline_textbbox((0, 0), text1, font=font)
        text_width = bbox[2] - bbox[0]
        text_height = bbox[3] - bbox[1]
        img_width, img_height = img.size
        x = (img_width - text_width) // 2
        y = (img_height - text_height) // 2
        # Vẽ text lên ảnh với khoảng cách dòng
        line_spacing = int(font_size * 0.8)
        draw.multiline_text((x, y), text1, font=font, fill=(255, 255, 255, 255), align="center", spacing=line_spacing)
        # Tạo tên file thân thiện SEO: chữ thường, thay khoảng trắng bằng gạch ngang
        seo_name = text.replace("function ", "function-").replace("()", "-").replace(" ", "-").replace("_", "-").lower()
        if seo_name.endswith("-"):
            seo_name = seo_name[:-1]
        # Đường dẫn file PNG xuất ra
        output_path = os.path.join(output_dir, f'{seo_name}.png')
        # Xóa metadata không cần thiết (nếu có)
        if 'exif' in img.info:
            img.info.pop('exif')
        # Lưu ảnh dưới dạng PNG, tối ưu nén
        img.save(output_path, format='PNG', optimize=True)
    print("Đã tạo xong ảnh PNG tối ưu SEO!")

def create_images_webp_from_text(
    background_path,
    text_list,
    output_dir='output_images',
    font_path='/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf',
    font_size=40,
    quality=80
):
    # Tạo thư mục lưu ảnh nếu chưa tồn tại
    os.makedirs(output_dir, exist_ok=True)
    for text in text_list:
        # Mở ảnh nền và chuyển sang RGBA
        img = Image.open(background_path).convert('RGBA')
        draw = ImageDraw.Draw(img)
        # Tạo font chữ
        font = ImageFont.truetype(font_path, font_size)
        # Chuẩn bị nội dung text, thêm dòng mô tả
        text1 = text + "\n trong chuỗi hàm PHP"
        # Tính toán kích thước text để căn giữa
        bbox = draw.multiline_textbbox((0, 0), text1, font=font)
        text_width = bbox[2] - bbox[0]
        text_height = bbox[3] - bbox[1]
        img_width, img_height = img.size
        x = (img_width - text_width) // 2
        y = (img_height - text_height) // 2
        # Vẽ text lên ảnh với khoảng cách dòng
        line_spacing = int(font_size * 0.8)
        draw.multiline_text((x, y), text1, font=font, fill=(255, 255, 255, 255), align="center", spacing=line_spacing)
        # Tạo tên file thân thiện SEO: chữ thường, thay khoảng trắng bằng gạch ngang
        seo_name = text.replace("function ", "function-").replace("()", "-").replace(" ", "-").replace("_", "-").lower()
        if seo_name.endswith("-"):
            seo_name = seo_name[:-1]
        # Đường dẫn file webp xuất ra
        output_path = os.path.join(output_dir, f'{seo_name}.webp')
        # Xóa metadata không cần thiết (nếu có)
        if 'exif' in img.info:
            img.info.pop('exif')
        # Lưu ảnh dưới dạng webp với chất lượng tối ưu cho SEO
        img.save(output_path, format='WEBP', quality=quality, method=6)
    print("Đã tạo xong ảnh webp tối ưu SEO!")

# Đường dẫn tới file ảnh nền
background_path = 'output_images/background-series-php-watermarked.png'

# Danh sách ký tự cần in lên ảnh
text_list = [
    'function range()',
    'function array()',
    'function array_key_exists()',
    'function in_array()',
    'function array_change_key_case()',
    'function array_chunk()',
    'function array_column()',
    'function array_combine()',
    'function array_count_values()',
    'function array_diff()',
    'function array_diff_assoc()',
    'function array_diff_key()',
    'function array_diff_uassoc()',
    'function array_diff_ukey()',
    'function array_fill()',
    'function array_fill_keys()',
    'function array_filter()',
    'function array_flip()',
    'function array_intersect()',
    'function array_intersect_assoc()',
    'function array_intersect_key()',
    'function array_intersect_uassoc()',
    'function array_intersect_ukey()',
    'function array_keys()',
    'function array_map()',
    'function array_merge()',
    'function array_merge_recursive()',
    'function array_multisort()',
    'function array_pad()',
    'function array_pop()',
    'function array_product()',
    'function array_push()',
    'function array_rand()',
    'function array_reduce()',
    'function array_replace()',
    'function array_replace_recursive()',
    'function array_reverse()',
    'function array_search()',
    'function array_shift()',
    'function array_slice()',
    'function array_splice()',
    'function array_sum()',
    'function array_udiff()',
    'function array_udiff_assoc()',
    'function array_udiff_uassoc()',
    'function array_uintersect()',
    'function array_uintersect_assoc()',
    'function array_uintersect_uassoc()',
    'function array_unique()',
    'function array_unshift()',
    'function array_values()',
    'function array_walk()',
    'function array_walk_recursive()',
    'function arsort()',
    'function asort()',
    'function compact()',
    'function count()',
    'function current()',
    'function each()',
    'function end()',
    'function extract()',
    'function key()',
    'function krsort()',
    'function ksort()',
    'function list()',
    'function natcasesort()',
    'function natsort()',
    'function next()',
    'function pos()',
    'function prev()',
    'function reset()',
    'function rsort()',
    'function shuffle()',
    'function sizeof()',
    'function sort()',
    'function uasort()',
    'function uksort()',
    'function usort()',
    'function affected_rows()',
    'function autocommit()',
    'function begin_transaction()',
    'function change_user()',
    'function character_set_name()',
    'function close()',
    'function commit()',
    'function connect()',
    'function connect_errno()',
    'function connect_error()',
    'function data_seek()',
    'function debug()',
    'function dump_debug_info()',
    'function errno()',
    'function error()',
    'function error_list()',
    'function fetch_all()',
    'function fetch_array()',
    'function fetch_assoc()',
    'function fetch_field()',
    'function fetch_field_direct()',
    'function fetch_fields()',
    'function fetch_lengths()',
    'function fetch_object()',
    'function fetch_row()',
    'function field_count()',
    'function field_seek()',
    'function get_charset()',
    'function get_client_info()',
    'function get_client_stats()',
    'function get_client_version()',
    'function get_connection_stats()',
    'function get_host_info()',
    'function get_proto_info()',
    'function get_server_info()',
    'function get_server_version()',
    'function info()',
    'function init()',
    'function insert_id()',
    'function kill()',
    'function more_results()',
    'function multi_query()',
    'function next_result()',
    'function options()',
    'function ping()',
    'function poll()',
    'function prepare()',
    'function query()',
    'function real_connect()',
    'function real_escape_string()',
    'function real_query()',
    'function reap_async_query()',
    'function refresh()',
    'function rollback()',
    'function select_db()',
    'function set_charset()',
    'function set_local_infile_default()',
    'function set_local_infile_handler()',
    'function sqlstate()',
    'function ssl_set()',
    'function stat()',
    'function stmt_init()',
    'function store_result()',
    'function thread_id()',
    'function thread_safe()',
    'function use_result()',
    'function warning_count()',
    'function checkdate()',
    'function date_add()',
    'function date_create_from_format()',
    'function date_create()',
    'function date_date_set()',
    'function date_default_timezone_get()',
    'function date_default_timezone_set()',
    'function date_diff()',
    'function date_format()',
    'function date_get_last_errors()',
    'function date_interval_create_from_date_string()',
    'function date_interval_format()',
    'function date_isodate_set()',
    'function date_modify()',
    'function date_offset_get()',
    'function date_parse_from_format()',
    'function date_parse()',
    'function date_sub()',
    'function date_sun_info()',
    'function date_sunrise()',
    'function date_sunset()',
    'function date_time_set()',
    'function date_timestamp_get()',
    'function date_timestamp_set()',
    'function date_timezone_get()',
    'function date_timezone_set()',
    'function date()',
    'function getdate()',
    'function gettimeofday()',
    'function gmdate()',
    'function gmmktime()',
    'function gmstrftime()',
    'function idate()',
    'function localtime()',
    'function microtime()',
    'function mktime()',
    'function strftime()',
    'function strptime()',
    'function strtotime()',
    'function time()',
    'function timezone_abbreviations_list()',
    'function timezone_identifiers_list()',
    'function timezone_location_get()',
    'function timezone_name_from_ abbr()',
    'function timezone_name_get()',
    'function timezone_offset_get()',
    'function timezone_open()',
    'function timezone_transitions_get()',
    'function timezone_version_get()',
    'function real_escape_string()',
    'function real_query()',
    'function reap_async_query()',
    'function refresh()',
    'function rollback()',
    'function select_db()',
    'function set_charset()',
    'function set_local_infile_default()',
    'function set_local_infile_handler()',
    'function sqlstate()',
    'function ssl_set()',
    'function stat()',
    'function stmt_init()',
    'function store_result()',
    'function thread_id()',
    'function thread_safe()',
    'function use_result()',
    'function warning_count()',
    'function checkdnsrr()',
    'function closelog()',
    'function dns_check_record()',
    'function dns_get_mx()',
    'function dns_get_record()',
    'function fsockopen()',
    'function gethostbyaddr()',
    'function gethostbyname()',
    'function gethostbynamel()',
    'function gethostname()',
    'function getmxrr()',
    'function getprotobyname()',
    'function getprotobynumber()',
    'function getservbyname()',
    'function getservbyport()',
    'function header_register_callback()',
    'function header_remove()',
    'function header()',
    'function headers_list()',
    'function headers_sent()',
    'function http_response_code()',
    'function inet_ntop()',
    'function inet_pton()',
    'function ip2long()',
    'function long2ip()',
    'function openlog()',
    'function pfsockopen()',
    'function setcookie()',
    'function setrawcookie()',
    'function socket_get_status()',
    'function socket_set_blocking()',
    'function socket_set_timeout()',
    'function syslog()',
    'function addcslashes()',
    'function addslashes()',
    'function bin2hex()',
    'function chop()',
    'function chr()',
    'function chunk_split()',
    'function convert_cyr_string()',
    'function convert_uudecode()',
    'function convert_uuencode()',
    'function count_chars()',
    'function crc32()',
    'function crypt()',
    'function echo()',
    'function explode()',
    'function fprintf()',
    'function get_html_translation_table()',
    'function hebrev()',
    'function hebrevc()',
    'function hex2bin()',
    'function html_entity_decode()',
    'function htmlentities()',
    'function htmlspecialchars_decode()',
    'function htmlspecialchars()',
    'function implode()',
    'function join()',
    'function lcfirst()',
    'function levenshtein()',
    'function localeconv()',
    'function ltrim()',
    'function md5()',
    'function md5_file()',
    'function metaphone()',
    'function money_format()',
    'function nl_langinfo()',
    'function nl2br()',
    'function number_format()',
    'function ord()',
    'function parse_str()',
    'function print()',
    'function printf()',
    'function quoted_printable_decode()',
    'function quoted_printable_encode()',
    'function quotemeta()',
    'function rtrim()',
    'function setlocale()',
    'function sha1()',
    'function sha1_file()',
    'function similar_text()',
    'function soundex()',
    'function sprintf()',
    'function sscanf()',
    'function str_getcsv()',
    'function str_ireplace()',
    'function str_pad()',
    'function str_repeat()',
    'function str_replace()',
    'function str_rot13()',
    'function str_shuffle()',
    'function str_split()',
    'function str_word_count()',
    'function strcasecmp()',
    'function strchr()',
    'function strcmp()',
    'function strcoll()',
    'function strcspn()',
    'function strip_tags()',
    'function stripcslashes()',
    'function stripslashes()',
    'function stripos()',
    'function stristr()',
    'function strlen()',
    'function strnatcasecmp()',
    'function strnatcmp()',
    'function strncasecmp()',
    'function strncmp()',
    'function strpbrk()',
    'function strpos()',
    'function strrchr()',
    'function strrev()',
    'function strripos()',
    'function strrpos()',
    'function strspn()',
    'function strstr()',
    'function strtok()',
    'function strtolower()',
    'function strtoupper()',
    'function strtr()',
    'function substr()',
    'function substr_compare()',
    'function substr_count()',
    'function substr_replace()',
    'function trim()',
    'function ucfirst()',
    'function ucwords()',
    'function vfprintf()',
    'function vprintf()',
    'function vsprintf()',
    'function wordwrap()',
    'function abs()',
    'function acos()',
    'function acosh()',
    'function asin()',
    'function asinh()',
    'function atan()',
    'function atan2()',
    'function atanh()',
    'function base_convert()',
    'function bindec()',
    'function ceil()',
    'function cos()',
    'function cosh()',
    'function decbin()',
    'function dechex()',
    'function decoct()',
    'function deg2rad()',
    'function exp()',
    'function expm1()',
    'function floor()',
    'function fmod()',
    'function getrandmax()',
    'function hexdec()',
    'function hypot()',
    'function intdiv()',
    'function is_finite()',
    'function is_infinite()',
    'function is_nan()',
    'function lcg_value()',
    'function log()',
    'function log10()',
    'function log1p()',
    'function max()',
    'function min()',
    'function mt_getrandmax()',
    'function mt_rand()',
    'function mt_srand()',
    'function octdec()',
    'function pi()',
    'function pow()',
    'function rad2deg()',
    'function rand()',
    'function round()',
    'function sin()',
    'function sinh()',
    'function sqrt()',
    'function srand()',
    'function tan()',
    'function tanh()',
    'function basename()',
    'function chgrp()',
    'function chmod()',
    'function chown()',
    'function clearstatcache()',
    'function copy()',
    'function delete()',
    'function dirname()',
    'function disk_free_space()',
    'function disk_total_space()',
    'function diskfreespace()',
    'function fclose()',
    'function feof()',
    'function fflush()',
    'function fgetc()',
    'function fgetcsv()',
    'function fgets()',
    'function file()',
    'function file_exists()',
    'function file_get_contents()',
    'function file_put_contents()',
    'function fileatime()',
    'function filectime()',
    'function filegroup()',
    'function fileinode()',
    'function filemtime()',
    'function fileowner()',
    'function fileperms()',
    'function filesize()',
    'function filetype()',
    'function flock()',
    'function fnmatch()',
    'function fopen()',
    'function fpassthru()',
    'function fputcsv()',
    'function fputs()',
    'function fread()',
    'function fscanf()',
    'function fseek()',
    'function fstat()',
    'function ftell()',
    'function ftruncate()',
    'function fwrite()',
    'function glob()',
    'function is_dir()',
    'function is_executable()',
    'function is_file()',
    'function is_link()',
    'function is_readable()',
    'function is_uploaded_file()',
    'function is_writable()',
    'function is_writeable()',
    'function lchgrp()',
    'function lchown()',
    'function link()',
    'function linkinfo()',
    'function lstat()',
    'function mkdir()',
    'function move_uploaded_file()',
    'function parse_ini_file()',
    'function parse_ini_string()',
    'function pathinfo()',
    'function pclose()',
    'function popen()',
    'function readfile()',
    'function readlink()',
    'function realpath()',
    'function realpath_cache_get()',
    'function realpath_cache_size()',
    'function rename()',
    'function rewind()',
    'function rmdir()',
    'function set_file_buffer()',
    'function stat()',
    'function symlink()',
    'function tempnam()',
    'function tmpfile()',
    'function touch()',
    'function umask()',
    'function unlink()',
]

# create_images_from_text(background_path, text_list)

create_images_webp_from_text(background_path, text_list)